### ISSUE TITLE
Another partition

### ISSUE THREAD

**Issue by Anton111111** [arnoldthebat/chromiumos#106]
Hello! I have ntfs separate partition on hdd with my files (This partition used in windows). 
Can i get access to files from this partition in chromeos ?

**Comment by NoodleCommits** [comment]
You might not be able to access the Windows (NTFS) partition from Chromium OS. I tried [Neverware's Cloudready](https://www.neverware.com/#cloudready-introduction) and I was able to access my files on my NTFS partition, probably because of dual-boot stuff.

However, I was unable to use Arnold's Chromium OS builds to access my NTFS partition.
You could try, but these were my experiences.

Short Answer: Maybe not... At least not with Arnold's builds.

**Comment by arnoldthebat** [comment]
Not supported, sorry. I believe Neverware have removed dualboot as well
