### ISSUE TITLE
dell latitude d610 won't boot

### ISSUE THREAD

**Issue by dallasrules** [arnoldthebat/chromiumos#109]
I have a dell latitude d610 that I am trying to install on.  when I try to boot from the usb drive, it starts Chromium, they says attempting to repair system, please wait.  Then it just reboots, so there is an endless loop.  I downloaded the Cx86OS-20170113010102.img file.  The same thing happened when I try to do it from the cloud ready site.  Can you let me know if I need a different file, or if it just can't be installed on this laptop.

**Comment by haxalicious** [comment]
You aren't providing very much info about the situation, so I don't have a good idea of what the problem might be, but here are some general troubleshooting tips that work most of the time:

1. Are you running on a 32-bit or 64-bit processor? Make sure to install the correct version for your CPU architecture.

2. How did you install it? If you are on Windows use Win32 Disk Imager to install it to the USB, if you are on GNU/Linux use dd. Other imaging tools like UNetbootin or LiLi USB Creator will not work, as they do not create the proper partitions. If it is installed correctly, Windows will either not recognize it or it will see it as a lower capacity USB than it actually is. If you want to install it on your HDD/SSD and want to then reuse the USB for something else, you will need to use a tool to reformat it (eg. GParted), just normally formatting it on Windows will not format the entire USB because it doesn't see the Chromium OS partitions as writable space. 

3. If you are running on UEFI bios, try disabling Secure Boot and see if that fixes it.

Hope this helped!

**Comment by arnoldthebat** [comment]
Closing off since the processor is 32 bit only. This will never work
