### ISSUE TITLE
Does not boot due to nVidia Quadro FX 770M

### ISSUE THREAD

**Issue by mzs112000** [arnoldthebat/chromiumos#132]
It does not boot on my laptop.
I suspect that this is due to graphics drivers not being compatible with my GPU.
It gets to the "Chromium" white splash screen, and then freezes forever.
It does this on every build so far.

**Comment by guilala** [comment]
Bumping the same problem with a Dell m3800: NVIDIA Quadro K1100M / Intel HD 4600 hybrid graphics. I am trying to run Linux on this expensive hardware for years now. The only way for me to get Nvidia gpu graphics, is running Debian, Xorg, and Nvidia's proprietary drivers. High frame rates like that, but visual tearing issues due to Xorg limitations. I was hoping Chromium OS would be a solution since it now uses Freon,.. apparently not :-/. Anyone knows how to get this type of hybrid graphics hardware to use it's Nvidia hardware? This type of hardware is very common, but probably never used for official Chromebooks?

**Comment by mzs112000** [comment]
Will nVidia graphics ever work on Chromium OS?

**Comment by arnoldthebat** [comment]
Should be fixed now in special build R64
