### ISSUE TITLE
Surface Pro 3 Marvell WiFI support not working

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#14]

**Comment by espectalll** [comment]
Could this be solved, at least, by manually patching an already built image? I have a Surface Pro 2 and has the same problem - the drivers are blobs not preloaded on any Linux version, so they have to be downloaded from _git://git.marvell.com/mwifiex-firmware.git_... and that's about it. But because of that I am unable to boot up Chromium OS. And that's a shame.
