### ISSUE TITLE
MacBook Air model A1304 not working

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#22]
No controller found
Incomplete mode parameter data
assuming drive cache: write through
no bios dp data

**Comment by AlvaroMartinezB** [comment]
Hi arnold! I can also confirm that the latest special build isnt working on this model of MacBook Air... I can help you test anything if you want to, and I will also search for other solutions because apparently this issue ocurs  with any flavor of linux

**Comment by ASDFDSGFTSZG** [comment]
?issue workaround

Reproduce:
Insert USB
Boot to USB
Wait for max. 10 minutes
Remove USB
Wait for error message
Insert USB
Wait until boot logo

R46-7323 CAMD64

**Comment by arnoldthebat** [comment]
Yes, Ive seen this before. USB on macbooks does seem a tad flaky to say the least!

**Comment by AlvaroMartinezB** [comment]
I tried it, I kept getting the same error buried in a ton of errors reading some things (obviously because the USB was disconnected...) I left the USB disconnected for about 5 minutes, and I was still getting error 22. When I plugged in the drive, I just got some extra lines saying it had set some stuff to write... Then I just got the error again and again... Do you think installing directly to the hard drive would help? I'm willing to try it... I also already confirmed that my USB is in fact working by plugging it into a windows computer at school (Dell optiplex) and it worked like a charm... I hope we can solve this! It would be truly awesome!

**Comment by ASDFDSGFTSZG** [comment]
Don't install it. If it doesn't boot from the USB, it wont boot from the hard drive. However, once it has boot from the USB, it will boot perfectly afterwards so only then can you install it on your hard drive.

When I tried it, I disconnected it for until the 'error messages' popped up. Try inserting the USB as soon as you see the white text.

**Comment by AlvaroMartinezB** [comment]
Okay okay so I will try to do it again... as soon as I get the first error (-22) I will disconnect the USB, and when I get all the errors (which usually happens imidiatelly) I'll conection again. Fingers crossed for it to work... is there any way to contact you more directly? If you are willing here's my email: alvaro.martinez.7c@gmail.com

**Comment by AlvaroMartinezB** [comment]
I was trying with the 32 bit version, and I finally gave up to it booting... So I am now trying with the 64 bit version, and still the same... I disconnect the USB when I get the first few error messages, and plug it back in a few seconds later.... Doesn't seem to work, am I doing something wrong?
![20150905_164903](https://cloud.githubusercontent.com/assets/14044330/9701426/0e9d20d8-53ee-11e5-803f-63aee9a39ae9.jpg)

**Comment by arnoldthebat** [comment]
I didn't mean take out the USB when its loaded, I mean to wait until the boot from USB hangs, then power off. Then change the USB slot the stick is plugged into and try again. If that fails, power off and place in the original slot. Its a bit haphazard but does seem to work.

Ill need to look at the kernel switches to fix this properly (I think) so bear with me

**Comment by mpipo** [comment]
Can confirm USB is flaky on MacBookPro11,1. USB randomly boots.

I'm using these for kernel boot params, might help:

```
insmod efi_gop
modprobe efivars

menuentry "Chromium OS" {
linux (hd1,gpt5)/boot/vmlinuz ro root=/dev/sda5 cros_efi cros_debug rootwait noresume noinitrd quiet i915.modeset=1 noapic
}
```

**Comment by AlvaroMartinezB** [comment]
How can I set those kernel parameters? I gave up on making it boot the way it was... i never got it to boot.

**Comment by mpipo** [comment]
In the bootloader (GRUB) select first option, press e, then replace everything after vmlinuz with mine (after vmlinuz too)

**Comment by AlvaroMartinezB** [comment]
Okay i tried it, this is what I wrote initially: 
![img_20151008_203049](https://cloud.githubusercontent.com/assets/14044330/10384023/e99744bc-6dfb-11e5-879a-3fb1a10be77d.jpg)

and i got this:
![img_20151008_203057](https://cloud.githubusercontent.com/assets/14044330/10384030/f70a4cfc-6dfb-11e5-896a-577a8adf9c6e.jpg)

I noticed that mine originally (besides having everything before vmlinuz different) it had a .A at the end of vmlinuz, so I wrote the .A back

![img_20151008_203136](https://cloud.githubusercontent.com/assets/14044330/10384051/30d19e36-6dfc-11e5-932e-629c424b8a4c.jpg)
 
getting this as a result:

![img_20151008_202540](https://cloud.githubusercontent.com/assets/14044330/10384054/3a50789c-6dfc-11e5-8f91-d0c85b5e96cb.jpg)

I am no expert, but I can tell that a Kernel panic is not good. Could you please take a look at what i got and help me find a solution? I would really appreciate it!

**Comment by mpipo** [comment]
Welp, about the .A, I forgot to mention that it won't be the exact same as mine. Really sorry about that. I installed my ChromiumOS on the SSD, so some things are different.

Now, the kernel panic is caused by wrong root partition. You need to swap out my root=/dev/sda5 with root=/dev/sdwhat you had initially.

**Comment by AlvaroMartinezB** [comment]
Okay I'll do that, thank you very much!

**Comment by AlvaroMartinezB** [comment]
Just one thing... My "root=" is a very long code, should i put this? it does not include /dev/sd...
![img_20151008_213005](https://cloud.githubusercontent.com/assets/14044330/10384631/08b88cea-6e04-11e5-831b-1a2dc23e9ef7.jpg)
 
I will try to do it with this long code, it might be because I am booting from a USB drive and not directly from the SSD

**Comment by mpipo** [comment]
Whoops, completely forgot about this issue!

Yes, please do that.

**Comment by arnoldthebat** [comment]
Closing this off since its ancient and users need to retest and report if its still an issue
