### ISSUE TITLE
Special build 72 no GDrive support

### ISSUE THREAD

**Issue by Snowflake6** [arnoldthebat/chromiumos#234]
Installing Special build 72 on an MSI all-in-one PC with nVidia graphics.  When booted from the USB, I briefly saw a "Google Drive" link in the file explorer, but it disappeared.  Installing to the hard drive, No Google Drive in explorer, and although I saw "Music", "Pictures", "Videos" briefly, they seem to have disappeared now too.  I thought Google Drive integration was included in the bat builds?  Am I missing something?

**Comment by arnoldthebat** [comment]
Might be related to http://www.chromium.org/developers/how-tos/api-keys - see the section on 'Rate limit when signing into Google account from Chromium builds'

Im building a new variant to test the theory....

**Comment by arnoldthebat** [comment]
None yet. Still trying to fix it. FUSE permissions appear to be well broken currently so Im resetting my build...

**Comment by arnoldthebat** [comment]
Bad news. This looks to have gone closed source so not going to be a trivial fix if its even possible...

GDocs and GSheets will still work from the browser however...

ref: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-os-dev/MxYBMUnh80g for ref.

Ill leave this open to remind me to try to hack around it, but this will be longer term fixes sadly...

**Comment by Snowflake6** [comment]
Aw, crap.  Google does some darned annoying things to people who really want to use their services.  Chromium has much less value to me without some useful combination of GDrive, Linux, and Android support...

**Comment by Snowflake6** [comment]
FYI - I tried Cloudready on the weekend and found that their latest build (R72-based) has GDrive functioning.  If there's anything I could look at there that would help you figure this out let me know (or if you have a spare PC that you want to try installing Cloudready on you could check it out locally).

**Comment by AdamKearn** [comment]
It looks like he is just missing the Google Drive API.
[https://console.cloud.google.com/apis/library/drive.googleapis.com?q=drive](https://console.cloud.google.com/apis/library/drive.googleapis.com?q=drive)

There is a guide here with a list of API's that need enabling.
[https://www.chromium.org/developers/how-tos/api-keys](https://www.chromium.org/developers/how-tos/api-keys)
I would also add the `Directory API` (which isn't on that list) but would allow users to enroll their devises. 

If you want a work around for now (note this isn't permanent) you can can change the values in this file `/etc/chrome_dev.conf` to `=no` which will allow all API's to be used.
**You will have to mount the rootfs as **`RW`** in order to do this.**
```
GOOGLE_API_KEY=no
GOOGLE_DEFAULT_CLIENT_ID=no
GOOGLE_DEFAULT_CLIENT_SECRET=no
```

**Comment by Snowflake6** [comment]
@AdamKearn that sounds like something so fundamental that @arnoldthebat has probably thought of it... But hey, brain farts happen.  @arnoldthebat, is this something you can try?  I've got a working platform now with CloudReady but I would consider switching back to ATB if I had gDrive support again.

Although, CR seems to have more stable support for my graphics system... No tearing or browser crashes so far at least... That did happen with ATB Special 72.

**Comment by arnoldthebat** [comment]
Hi All

I do indeed build in the keys for all the supported API keys as per
https://www.chromium.org/developers/how-tos/api-keys plus additional ones
for enrolment support.

Neverware have direct backing from Google so its not really unexpected for
them to have access to the proprietary blobs.

Nothing I can do really Im afraid. Hopefully Google will release the blobs
in the futire as Mike Frysinger stated on Groups

Ill leave the bug open for the moment since I might find some time to try
to cobble something in the future...

**Comment by Snowflake6** [comment]
Excellent, thanks @arnoldthebat for checking.  Let's hope Google opens the kimono a bit in future.

**Comment by ryanbin7** [comment]
@AdamKearn tried setting values in `/etc/chrome_dev.conf` to `=no` but couldn't log in after. Kept saying "something went wrong" after verifying on my phone. Same result using Google Authenticator. Removing changes from `chrome_dev.conf` let me log in again. Did I do something wrong?

**Comment by arnoldthebat** [comment]
Closing this since I cannot fix closed source FUSE drivers. Sorry!
