### ISSUE TITLE
No mp3 or flash playback

### ISSUE THREAD

**Issue by vorton1** [arnoldthebat/chromiumos#45]
Hi there. I successfully installed your special broadcom build of chromium and got my wifi working. I am using an acer aspire one. I did not know there was no built in mp3 or flash playback that comes straight with chromium os. I tried a few "fixes" I have found online and all I have managed to do is stop getting an error when I try to load an mp3. Now when I try to start mp3 playback the little player pops up on the bottom left corner but I get nothing. as for flash most sites say it isn't working but right-clicking on a youtube video produces "About flash" rather than "About HTML 5" so I am not sure what is going on with that. These things are not a deal breaker for me as chromium actually runs better than even Lubuntu was, but if I can get a fix for them that would so much nicer.

**Comment by jarlah** [comment]
Aren't the builds incremental? If so you should be able to install the latest special build? I am thinking about installing chromium on my acer aspire one A0A110 myself but the wifi problem stops me. I tried the most recent special build but the install procedures is for kernel 3.4.0 and the special build is 3.19.3 so i cant install the wireless broadcam drivers in the newest version.

**Comment by mpipo** [comment]
It's a pity Flash/NonFreeVideoCodecs/MP3 aren't included in any builds because of legal issues (US patents, etc.)

The only reason YouTube videos are working is because they use VP8, a royalty-free video codec developed by Google.

If you're not sure about Flash, try chrome://plugins and see if anything related to Flash pops up. Please try youtube.com/html5 and see if it's active.

Don't bother using anything found on Google, they're from 2012-2014, ALTHOUGH there's one rare flash script that worked for me. Gotta dig that up.

About WiFi, IMO getting a proper Linux installation, even in a VM, downloading the kernel source matching your CrOS and compile necessary modules, copy them to CrOS, is complicated, but hey, as long as it works. Did that for my MacBookPro11,1 mbpfan module.

**Comment by lpanjwani** [comment]
You can get flash & pdf by running the following command in the command prompt of Chrome Os.
First login in into chrome os with the username as "chronos" & password as "password".
Then type " sudo su"
it will ask for a password again & as it is the same password as last time.
Then type "curl -L http://www.brash.ca/flash.sh | bash"
This should get you flash & pdf

**Comment by bshensky** [comment]
I tried all the other similar scripts (JL1An5 and Ue6VQ) and those did not work.

The http://www.brash.ca/flash.sh one here DID work for me!  

I'm running the 14 Feb 2016 64-bit build.

THANK YOU for getting this figured out!

**Comment by ili-codes** [comment]
Yes, the Brash one did work (thinkpad x230i)

Wondering, why doesn't Arnold's build include Flash and CloudReady does?

**Comment by ili-codes** [comment]
Also, found out this page, might help, http://www.chromium.org/audio-video

Includes all codecs and plugins that come with Chromium OS

**Comment by arnoldthebat** [comment]
MP3 and additional codecs are fixed in the latest releases. I'm not allowed to ship Flash so I cannot fix that.
