### ISSUE TITLE
Nvidia Graphics Support needed

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#6]

**Comment by Trucido** [comment]
I know this is an old issue but still "Open" but the Nouveau open source nvidia driver works fairly decently in my limited testing on a nvidia-legacy card. Maybe we could poke around Neverware CloudReady to see how they implement Nouveau (I noticed they use kernel 4.4.79 with extra drivers, though not sure how much they've backported).  
  
If this has already been fixed/implemented then sorry for the noise

**Comment by Trucido** [comment]
Found the issue with nvidia, missing nouveau_drv.so (and associated 'nv' one too i think) in /usr/lib64/xorg/modules/drivers/  
theoretically it should work if it was compiled with nv/nouveau support, the firmware is present in /lib/firmware/ and the kernel driver is present as well and it loads fine for framebuffer. maybe eventually i'll try compiling my own build...

**Comment by Trucido** [comment]
I discovered that neverware left in their /var/db stuff which includes all of the ebuilds, environments, USE flags and other things used for their build (which is fully working with wayland/Freon on a lot of nvidia, AMD, and of course Intel GPUs).  
It may be as simple as enabling some USE flags perhaps, though it looks like some of the ebuilds were modified as well. I've uploaded a tarball below if anyone wants to take a crack at this
  
[var_overlay.zip](https://github.com/arnoldthebat/chromiumos/files/1224054/var_overlay.zip)
  
There's also some interesting stuff in their dev_image directory as well, and some scripts in `/opt/neverware` though I'm not sure of the licensing on the latter in order to share it  
  
Not sure if relevant but the kernel cmdline is: `BOOT_IMAGE=foo boot=local rootwait ro noresume noswap loglevel=3 noinitrd console= root=PARTUUID=foo i915.modeset=1 cros_legacy cros_debug`  
  
and below is a (huge wall of text) grep for nouveau and nvidia from `var/db/pkg/*/*` (sorry I'd format it better but i'm doing this mobile from a chromebook)
  
`media-libs/mesa-13.1.0-r3/IUSE:video_cards_intel video_cards_radeon video_cards_radeonsi video_cards_mach64 video_cards_mga video_cards_nouveau video_cards_r128 video_cards_savage video_cards_sis video_cards_vmware video_cards_tdfx video_cards_via video_cards_freedreno +classic debug dri egl +gallium -gbm gles1 gles2 +llvm +nptl pic selinux shared-glapi kernel_FreeBSD vulkan xlib-glx X cros_host cros_workon_tree_286d9bc36c9a9302b6578a2d791a97f70c98ff74 profiling`
  
`media-libs/mesa-13.1.0-r3/USE:abi_x86_64 amd64 classic dri egl elibc_glibc gallium gbm gles2 kernel_linux kernel_sources llvm nptl shared-glapi userland_GNU video_cards_intel video_cards_nouveau video_cards_radeon video_cards_radeonsi`
  
`media-libs/mesa-13.1.0-r3/mesa-13.1.0-r3.ebuild:VIDEO_CARDS="${INTEL_CARDS} ${RADEON_CARDS} mach64 mga nouveau r128 savage sis vmware tdfx via freedreno"`
  
`media-libs/mesa-13.1.0-r3/mesa-13.1.0-r3.ebuild:                driver_enable video_cards_nouveau nouveau`
  
`media-libs/mesa-13.1.0-r3/mesa-13.1.0-r3.ebuild:                gallium_driver_enable video_cards_nouveau nouveau`
  
`media-libs/mesa-13.1.0-r3/mesa-13.1.0-r3.ebuild:        local gallium_drivers_files=( i915_dri.so nouveau_dri.so r300_dri.so r600_dri.so msm_dri.so swrast_dri.so )`
  
`media-libs/mesa-13.1.0-r3/mesa-13.1.0-r3.ebuild:        local classic_drivers_files=( i810_dri.so i965_dri.so nouveau_vieux_dri.so radeon_dri.so r200_dri.so )`
  
`sys-kernel/chromeover-kernel-4.4.14-r33/IUSE: [snip] builtin_fw_t210_nouveau [snip]`
  
`sys-kernel/chromeover-kernel-4.4.14-r33/chromeover-kernel-4.4.14-r33.ebuild:# For mmiotracing drivers. Such as nouveau for RE.`
  
`x11-apps/intel-gpu-tools-1.15/IUSE:test-programs unwind video_cards_nouveau`
  
`x11-apps/intel-gpu-tools-1.15/IUSE_EFFECTIVE:abi_x86_64 alpha amd64 amd64-fbsd amd64-linux arm arm-linux arm64 elibc_AIX elibc_Cygwin elibc_Darwin elibc_DragonFly elibc_FreeBSD elibc_HPUX elibc_Interix elibc_NetBSD elibc_OpenBSD elibc_SunOS elibc_Winnt elibc_glibc elibc_mintlib elibc_musl elibc_uclibc hppa hppa-hpux ia64 ia64-hpux ia64-linux kernel_AIX kernel_Darwin kernel_FreeBSD kernel_HPUX kernel_NetBSD kernel_OpenBSD kernel_SunOS kernel_Winnt kernel_freemint kernel_linux m68k m68k-mint mips nios2 ppc ppc-aix ppc-macos ppc-openbsd ppc64 ppc64-linux prefix prefix-guest riscv s390 sh sparc sparc-fbsd sparc-solaris sparc64-freebsd sparc64-solaris test-programs unwind userland_BSD userland_GNU video_cards_nouveau x64-cygwin x64-freebsd x64-macos x64-openbsd x64-solaris x86 x86-cygwin x86-fbsd x86-freebsd x86-interix x86-linux x86-macos x86-netbsd x86-openbsd x86-solaris x86-winnt  `
  
`x11-apps/intel-gpu-tools-1.15/USE:abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU video_cards_nouveau`
  
`x11-apps/intel-gpu-tools-1.15/intel-gpu-tools-1.15.ebuild:IUSE="test-programs unwind video_cards_nouveau"`
  
`x11-apps/intel-gpu-tools-1.15/intel-gpu-tools-1.15.ebuild:      >=x11-libs/libdrm-2.4.64[video_cards_intel,video_cards_nouveau?]`
  
`x11-apps/intel-gpu-tools-1.15/intel-gpu-tools-1.15.ebuild:              $(use_enable video_cards_nouveau nouveau)`
  
`x11-libs/libdrm-2.4.70-r21/IUSE:video_cards_amdgpu video_cards_exynos video_cards_freedreno video_cards_intel video_cards_mediatek video_cards_nouveau video_cards_omap video_cards_radeon video_cards_vmware video_cards_rockchip libkms manpages +udev static-libs cros_host cros_workon_tree_aee2be3e199a878e04c46a01072c5bd101cf6c57 profiling`
  
`x11-libs/libdrm-2.4.70-r21/USE:abi_x86_64 amd64 elibc_glibc kernel_linux kernel_sources libkms udev userland_GNU video_cards_amdgpu video_cards_intel video_cards_nouveau video_cards_radeon`
  
`x11-libs/libdrm-2.4.70-r21/libdrm-2.4.70-r21.ebuild:VIDEO_CARDS="amdgpu exynos freedreno intel mediatek nouveau omap radeon vmware rockchip"`
  
`x11-libs/libdrm-2.4.70-r21/libdrm-2.4.70-r21.ebuild:            $(use_enable video_cards_nouveau nouveau)`
  
`sys-apps/flashrom-0.9.4-r477/IUSE:+atahpt +bitbang_spi +buspirate_spi dediprog +drkaiser +dummy +fdtmap ft2232_spi +gfxnvidia +internal +linux_i2c +linux_mtd +linux_spi +nic3com +nicintel +nicintel_spi +nicnatsemi +nicrealtek +ogp_spi +raiden_debug_spi +rayer_spi +satasii +satamv +serprog static use_os_timer +wiki cros_host cros_host cros_workon_tree_7dc7fbb0bf60fb5cf5c1ea97b5c21f39b2342851 profiling`
`sys-apps/flashrom-0.9.4-r477/USE:abi_x86_64 amd64 atahpt bitbang_spi buspirate_spi drkaiser dummy elibc_glibc fdtmap gfxnvidia internal kernel_linux kernel_sources linux_i2c linux_mtd linux_spi nic3com nicintel nicintel_spi nicnatsemi nicrealtek ogp_spi raiden_debug_spi rayer_spi satamv satasii serprog static userland_GNU wiki`
  
`sys-apps/flashrom-0.9.4-r477/flashrom-0.9.4-r477.ebuild:+dummy +fdtmap ft2232_spi +gfxnvidia +internal +linux_i2c +linux_mtd +linux_spi`
  
`sys-apps/flashrom-0.9.4-r477/flashrom-0.9.4-r477.ebuild:        gfxnvidia? ( sys-apps/pciutils[static-libs(+)] )`
  
`sys-apps/flashrom-0.9.4-r477/flashrom-0.9.4-r477.ebuild:                ft2232_spi gfxnvidia linux_i2c linux_mtd linux_spi \`
  
`x11-libs/libva-1.7.1-r1/IUSE:+drm egl opengl vdpau wayland X video_cards_dummy video_cards_nvidia video_cards_intel video_cards_fglrx abi_x86_32 abi_x86_64 abi_x86_x32 abi_mips_n32 abi_mips_n64 abi_mips_o32 abi_ppc_32 abi_ppc_64 abi_s390_32 abi_s390_64`
  
`x11-libs/libva-1.7.1-r1/IUSE_EFFECTIVE:X abi_mips_n32 abi_mips_n64 abi_mips_o32 abi_ppc_32 abi_ppc_64 abi_s390_32 abi_s390_64 abi_x86_32 abi_x86_64 abi_x86_x32 alpha amd64 amd64-fbsd amd64-linux arm arm-linux arm64 drm egl elibc_AIX elibc_Cygwin elibc_Darwin elibc_DragonFly elibc_FreeBSD elibc_HPUX elibc_Interix elibc_NetBSD elibc_OpenBSD elibc_SunOS elibc_Winnt elibc_glibc elibc_mintlib elibc_musl elibc_uclibc hppa hppa-hpux ia64 ia64-hpux ia64-linux kernel_AIX kernel_Darwin kernel_FreeBSD kernel_HPUX kernel_NetBSD kernel_OpenBSD kernel_SunOS kernel_Winnt kernel_freemint kernel_linux m68k m68k-mint mips nios2 opengl ppc ppc-aix ppc-macos ppc-openbsd ppc64 ppc64-linux prefix prefix-guest riscv s390 sh sparc sparc-fbsd sparc-solaris sparc64-freebsd sparc64-solaris userland_BSD userland_GNU vdpau video_cards_dummy video_cards_fglrx video_cards_intel video_cards_nvidia wayland x64-cygwin x64-freebsd x64-macos x64-openbsd x64-solaris x86 x86-cygwin x86-fbsd x86-freebsd x86-interix x86-linux x86-macos x86-netbsd x86-openbsd x86-solaris x86-winnt`
  
`x11-libs/libva-1.7.1-r1/libva-1.7.1-r1.ebuild:VIDEO_CARDS="dummy nvidia intel fglrx"`
  
`x11-libs/libva-1.7.1-r1/libva-1.7.1-r1.ebuild:PDEPEND="video_cards_nvidia? ( x11-libs/libva-vdpau-driver[${MULTILIB_USEDEP}] )`

**Comment by arnoldthebat** [comment]
Hi @Trucido 

Fantastic work!

Ill take a look but I think the problem will be a lack of Freon drivers for Nouveau. These I believe need to be written specifically for the Freon stack. Hopefully Neverware will open source it, so Ill keep reviewing Gerrit in hope.

Other than that, as I get some time, Ill review the NW build and see what I can figure out from the above!

**Comment by Trucido** [comment]
From what I understand, Freon just runs on wayland+ozone directly from KMS (nouveau provides working KMS like intel and AMD). in theory it should utilize the same DRI/egl drivers and/or interfaces as any other, but I could be wrong. (like recent GNOME 3.xx releases, though they use Gallium3D for non-native apps I think? or maybe I'm getting names confused).  
My Fedora testbed shows these same files below that were present on neverware's build, though i'm unsure if there was any special hacking done to them on neverware:  
`/usr/lib64/libdrm_nouveau.so`  
`/usr/lib64/libdrm_nouveau.so.2`  
`/usr/lib64/libdrm_nouveau.so.2.0.0`  
`/usr/lib64/dri/nouveau_vieux_dri.so`   
`/usr/lib64/dri/nouveau_dri.so` 
^these were all present in neverware  

In addition, below is some possibly relevant misc files I found on the fedora box:  
  
kernel module on fedora box: (it's present and loaded in your builds in `lsmod`, but the module location must be located elsewhere):
`/usr/lib/modules/4.xx.x/kernel/drivers/gpu/drm/nouveau/nouveau.ko.xz`  
modules associated/loaded alongside Nouveau on the fedora box: (i'll have to compare to the `lsmod` on your builds but some might be built-ins):  
`nouveau` `i2c_algo_bit` `drm_kms_helper` `ttm` `drm` `video`  
`wmi` `dell_wmi` `mxm_wmi` `dell_laptop` (these are likely all mostly mobile/Dell related)  
  
Xorg X11 drivers (non-wayland):  
`/usr/lib64/xorg/modules/drivers/nouveau_drv.so`  
`/usr/lib64/dri/nouveau_drv_video.so` (I THINK this is only relevant to Xorg, or perhaps something with vdpau)  
`/usr/lib64/gallium-pipe/pipe_nouveau.so` (Gallium3D, likely only relevant to Linux desktops. wasn't on neverware)  
  
And the below files are vdpau related, which I never got working on fedora due to their mesa build, plus most of it requires some firmware files not available without extracting from an old nvidia binary file. youtube and netflix were playing great on neverware though, chrome://gpu showed hardware acceleration but I never verified it.  
`/usr/lib64/vdpau/libvdpau_nouveau.so.1`
`/usr/lib64/vdpau/libvdpau_nouveau.so.1.0`
`/usr/lib64/vdpau/libvdpau_nouveau.so.1.0.0`

**Comment by arnoldthebat** [comment]
Try this as a test please: http://srv11.arnoldthebat.co.uk/testing/chromiumos_image.bin

It has all the files you note....

**Comment by ggy7** [comment]
This guy [https://github.com/crosbuilder/CustomBuilds/releases/tag/R60-9592.85.2017_08_29_0007](url) build have integrated nouveau drivers, his chromium r60 boots with nvidia gtx670, but i got tearing when scrolling chromium os pages. So i don't know, would be this ifo useful or not. thnx

**Comment by mzs112000** [comment]
Are we any closer to getting Chromium OS to boot up with nVidia graphics?

**Comment by arnoldthebat** [comment]
Have a look at the latest r64 special builds. I have reports of nvidia working now....

https://arnoldthebat.co.uk/wordpress/2018/02/11/chromiumos-enhanced-special-build-r64-10176-b/

**Comment by mzs112000** [comment]
Seems to be working in the latest special build R64.
Only issue I have so far is HDD installation does not work(installer hangs, and eventually reboots the system without finishing the install.)

**Comment by mzs112000** [comment]
*note that the above comment only applies to my Dell Precision M4400 with a 160GB Toshiba HDD. It works fine on an HP pavilion guys with a 245GB Toshiba HDD and Intel i3.

**Comment by arnoldthebat** [comment]
Not sure on the HDD element to be fair. NVidia working is a great win tho!
